[package]
name = "lean-category-theory"
version = "0.1"
lean_version = "3.4.1"
path = "src"

[dependencies]
lean-tidy = {git = "https://github.com/semorrison/lean-tidy", rev = "1bd4a45e176ec8da3b999a760d1f13331ce41263"}
lean-category-theory-pr = {git = "https://github.com/semorrison/lean-category-theory-pr", rev = "591847d70c6a11c4d5561cd0eaf69b1fe85a70ab"}
