[package]
name = "lean-category-theory"
version = "0.1"
lean_version = "nightly-2018-06-21"
path = "src"

[dependencies]
lean-tidy = {git = "https://github.com/semorrison/lean-tidy", rev = "9cecf497e90db64b5ea140ad6ae1603976dcd402"}
lean-category-theory-pr = {git = "https://github.com/semorrison/lean-category-theory-pr", rev = "fc9e5df504eb6c3e99f9b4fcdd1cf2fc685f938b"}
