[package]
name = "lean-category-theory"
version = "0.1"
lean_version = "master"
path = "src"

[dependencies]
lean-tidy = {git = "https://github.com/semorrison/lean-tidy", rev = "643ae7bf3fc9039f24dd8118fc9c6edae7566ec8"}
