[package]
name = "lean-category-theory"
version = "0.1"
lean_version = "3.4.1"
path = "src"

[dependencies]
lean-tidy = {git = "https://github.com/semorrison/lean-tidy", rev = "16cfd0f50fc9b671938e130ade76b513e6b7ea12"}
lean-category-theory-pr = {git = "https://github.com/semorrison/lean-category-theory-pr", rev = "614ce03acb18d6e279596bc7fed3e652fd34daa5"}
