[package]
name = "lean-category-theory"
version = "0.1"
lean_version = "master"
path = "."

[dependencies]
lean-tidy = {git = "https://github.com/semorrison/lean-tidy", rev = "8f5d2fee8237ce86eee4bc28668d796aad945b52"}
