[package]
name = "lean-category-theory"
version = "0.1"
lean_version = "nightly-2018-04-06"
path = "src"

[dependencies]
lean-tidy = {git = "https://github.com/semorrison/lean-tidy", rev = "749471c7c37693e5e45d4b3e5e6bdea1d1e68b7a"}
lean-category-theory-pr = {git = "https://github.com/semorrison/lean-category-theory-pr", rev = "c5143a62193257d9393b016c2a7460e31edf7683"}
