[package]
name = "lean-category-theory"
version = "0.1"
lean_version = "nightly-2018-06-21"
path = "src"

[dependencies]
mathlib = {git = "https://github.com/leanprover-community/mathlib", rev = "318ec36d528e3f3c0ca7f43a0615d0116abf9c0f"}
lean-tidy = {git = "https://github.com/khoek/lean-tidy", rev = "d8f6c73524314e6b6eccaeb50ccff24d5002476b"}
