[package]
name = "lean-category-theory"
version = "0.1"
lean_version = "nightly-2018-06-21"
path = "src"

[dependencies]
lean-tidy = {git = "https://github.com/semorrison/lean-tidy", rev = "6ca5d7ee0d59f46ae266b2f0e52d11d67ef37058"}
lean-category-theory-pr = {git = "https://github.com/semorrison/lean-category-theory-pr", rev = "7d92bca90f3200232c92d9ae8b0a586b230898e9"}
