[package]
name = "lean-category-theory"
version = "0.1"
lean_version = "nightly-2018-04-20"
path = "src"

[dependencies]
lean-tidy = {git = "https://github.com/semorrison/lean-tidy", rev = "901abd2c37bfa0796efc76a98297c231b0a60832"}
lean-category-theory-pr = {git = "https://github.com/semorrison/lean-category-theory-pr", rev = "e9019d33655e0f68eb70587c5e566d8f67aebe1f"}
