[package]
name = "lean-category-theory"
version = "0.1"
lean_version = "nightly-2018-06-21"
path = "src"

[dependencies]
lean-tidy = {git = "https://github.com/semorrison/lean-tidy", rev = "c078b12ae1f557702123c1eb8752b805830ee21f"}
lean-category-theory-pr = {git = "https://github.com/semorrison/lean-category-theory-pr", rev = "3d09e1870927e9b4fa3fec9c9ba4e4e7026845d6"}
