[package]
name = "lean-category-theory"
version = "0.1"
lean_version = "master"
path = "src"

[dependencies]
lean-tidy = {git = "https://github.com/semorrison/lean-tidy", rev = "3aaee2fccfada7a1da70231c92d41c12e7d4b290"}
