[package]
name = "lean-category-theory"
version = "0.1"
lean_version = "nightly-2018-06-21"
path = "src"

[dependencies]
mathlib = {git = "git@github.com:leanprover-community/mathlib.git", rev = "ce46baf418d9c379f77d10af532a3f1a5a264ed5"}
lean-tidy = {git = "https://github.com/semorrison/lean-tidy", rev = "f82c45e5631e4532a7626282ab25bc5a54f16065"}
